In [2]:
! pip install numpy

In [6]:
import numpy as np
a = np.array([1,2,3,4],dtype='int32')
print(a)

[1 2 3 4]


In [9]:
b = np.array([[1,2,3,4,5,6,7,8],[11,22,33,44,55,66,77,88]])
print(b)

[[ 1  2  3  4  5  6  7  8]
 [11 22 33 44 55 66 77 88]]


In [27]:
# a.ndim
# b.ndim
# a.shape
# b.shape
a.dtype
b.dtype
c.dtype
c = np.array([[[1,2,3,4],[5,6,7,8],[9,8,7,6]]],dtype = 'int64')
print(c)
c.ndim
c.shape
c.dtype
c.itemsize
c.nbytes

[[[1 2 3 4]
  [5 6 7 8]
  [9 8 7 6]]]


96